export const CONTAINER_NAME = 'switchyard-action'

export function baseUrl(port: number): string {
  return `http://127.0.0.1:${port}/v1`
}

export interface RouteBundleParams {
  upstreamBaseUrl: string
  strongModel: string
  weakModel: string
  classifierModel: string
}

// Templated equivalent of the bundle's route.yaml: two tiers plus an
// LLM-classifier auto route with per-conversation pinning. The api_key
// placeholder is expanded by the Switchyard bundle loader from the
// container environment, so the key never appears in the file.
export function generateRouteBundle(p: RouteBundleParams): string {
  return `# Generated by switchyard-action from the base-url / strong-model /
# weak-model inputs. Pass route-config to replace this bundle entirely.

defaults:
  api_key: \${UPSTREAM_API_KEY}
  base_url: ${p.upstreamBaseUrl}
  format: openai
  extra_body: {}

routes:
  auto:
    type: deterministic
    profile: coding_agent
    classifier:
      model: ${p.classifierModel}
    strong:
      model: ${p.strongModel}
    weak:
      model: ${p.weakModel}
    fallback_target_on_evict: strong
    session_affinity: true
    affinity_warmup_turns: 2

  strong-only:
    type: model
    target: ${p.strongModel}

  weak-only:
    type: model
    target: ${p.weakModel}
`
}

export async function waitForHealth(port: number, timeoutMs: number): Promise<void> {
  const deadline = Date.now() + timeoutMs
  let lastError = ''
  while (Date.now() < deadline) {
    try {
      const res = await fetch(`http://127.0.0.1:${port}/health`, {
        signal: AbortSignal.timeout(3000),
      })
      if (res.ok) return
      lastError = `HTTP ${res.status}`
    } catch (e) {
      lastError = e instanceof Error ? e.message : String(e)
    }
    await new Promise((r) => setTimeout(r, 1000))
  }
  throw new Error(`router did not become healthy within ${timeoutMs / 1000}s (last error: ${lastError})`)
}
